### ISSUE TITLE
Wayland: Some minor regressions with borderless+fullscreen

### ISSUE THREAD

**Issue by wcout** [fltk/fltk#441]
Wayland behaves different as X11 with borderless+fullscreen windows:

1)  crashes when no wait_for_expose() is used before show()
2) does not give focus to the window when show() is **after** border(0)+fullscreen()

```cxx
#include <FL/Fl_Window.H>
#include <FL/Fl.H>

class Window : public Fl_Window {
public:
	Window(int w_, int h_, const char *l_ = 0) : Fl_Window(w_, h_, l_) {}
	virtual int handle( int e_ );
};

int Window::handle( int e_ ) {
	if ( FL_FOCUS == e_ ) {
		printf("FL_FOCUS\n");
	}
	if ( FL_UNFOCUS == e_ )	{
		printf("FL_UNFOCUS\n");
	}
	int c = Fl::event_key();
	if ( e_ == FL_KEYDOWN && Fl::get_key( c ) ) {
		printf("key %s\n", Fl::event_text());
		color(c);
		redraw();
	}
	return Fl_Window::handle( e_ );
}

int main(int argc, char *argv[]) {
	Window win( 500, 300 );
	win.resizable(win);
//	win.show(); // Issue #1: crashes (without previous wait_for_expose())
	win.border(0);
	win.fullscreen();
	win.show(); // Issue #2: does not give focus to window => keyboard not working
	return Fl::run();
}
```

**Comment by ManoloFLTK** [comment]
@wcout : should be good now after git pull. Can you confirm, please ?

**Comment by wcout** [comment]
It is fixed at least with my reproducer program.
But in one real program I have the effect, that no main window appears, but the program is running normally, getting timers and is drawing happily into a subwindow, while nothing is visible. However putting a `wait_for_expose()` after the `show()` of the main window fixes that.
I can't reproduce this situation with a simple program though, so it seems something very special.
You may close this issue anyway. Thank you.

**Comment by ManoloFLTK** [comment]
@wcout I will close this issue. I could debug the new problem you report if I can access the corresponding source code and it's not too complicated to build it.

**Comment by wcout** [comment]
Got it now!

It has to do with my program reacting to the initial window `FL_FOCUS` event and showing a "splash" screen synchronously from the window event handler. Thus FLTK is stuck in the function  `xdg_surface_configure` during that time and nothing goes on. Don't know if this a even valid action taken by program. It works with X11 (because it does not have this xdg callback). So I'm not sad if you say, this can't be fixed.

```
#1  0x000000000049bd26 in Fl_Unix_System_Driver::poll_or_select_with_delay(double) ()
#2  0x000000000049bf9e in Fl_Unix_System_Driver::wait(double) ()
#3  0x0000000000442abb in Fl::wait(double) (time_to_wait=0.10000000000000001) at Fl.cxx:482
#4  0x0000000000441d85 in splash(void*) (d_=0x7fffffffdc30) at focus.cxx:18
#5  0x0000000000441dfd in Window::handle(int) (this=0x7fffffffdc30, e_=6) at focus.cxx:30
#6  0x0000000000459ef1 in Fl_Widget::take_focus() (this=0x7fffffffdc30) at Fl_Widget.cxx:155
#7  0x0000000000443518 in fl_fix_focus() () at Fl.cxx:966
#8  0x0000000000443d51 in Fl::handle_(int, Fl_Window*) (e=6, window=0x7fffffffdc30) at Fl.cxx:1269
#9  0x00000000004439cd in Fl::handle(int, Fl_Window*) (e=6, window=0x7fffffffdc30) at Fl.cxx:1157
#10 0x0000000000473a8e in xdg_surface_configure(void*, xdg_surface*, uint32_t)
    (data=0x5382a0, xdg_surface=0x538380, serial=374)
    at drivers/Wayland/Fl_Wayland_Window_Driver.cxx:879
#11 0x00007ffff6db2ff5 in  () at /usr/lib/x86_64-linux-gnu/libffi.so.7
#12 0x00007ffff6db240a in  () at /usr/lib/x86_64-linux-gnu/libffi.so.7
#13 0x00007ffff7f593a8 in  () at /usr/lib/x86_64-linux-gnu/libwayland-client.so.0
#14 0x00007ffff7f55c48 in  () at /usr/lib/x86_64-linux-gnu/libwayland-client.so.0
#15 0x00007ffff7f5721c in wl_display_dispatch_queue_pending ()
    at /usr/lib/x86_64-linux-gnu/libwayland-client.so.0
#16 0x000000000049f4a4 in fd_callback(int, wl_display*) (unused=3, display=0x531190)
    at drivers/Wayland/Fl_Wayland_Screen_Driver.cxx:1051
#17 0x000000000049bdd0 in Fl_Unix_System_Driver::poll_or_select_with_delay(double) ()
#18 0x000000000049bf9e in Fl_Unix_System_Driver::wait(double) ()
#19 0x0000000000442abb in Fl::wait(double) (time_to_wait=1e+20) at Fl.cxx:482
#20 0x0000000000442ae3 in Fl::run() () at Fl.cxx:502
#21 0x0000000000441f6f in main(int, char**) (argc=1, argv=0x7fffffffde58) at focus.cxx:53
``` 
Here my reproducer:

```cxx
#include <FL/Fl_Window.H>
#include <FL/Fl.H>

class Window : public Fl_Window {
public:
	Window(int w_, int h_, const char *l_ = 0) : Fl_Window(w_, h_, l_) {}
	virtual int handle( int e_ );
};

void splash(void *d_)
{
	int Cnt = 50;
	Window *win = (Window *)d_;
	printf("splash\n");
	while ( Cnt-- )
	{
		win->color(FL_YELLOW);
		Fl::wait(0.1);
		printf(".");
		fflush(stdout);
	}
	win->color(FL_CYAN);
	win->redraw();
	printf("\nend splash\n");
}

int Window::handle( int e_ ) {
	if ( FL_FOCUS == e_ ) {
		printf("FL_FOCUS\n");
		splash( this );
	}
	if ( FL_UNFOCUS == e_ )	{
		printf("FL_UNFOCUS\n");
	}
	int c = Fl::event_key();
	if ( e_ == FL_KEYDOWN && Fl::get_key( c ) ) {
		printf("key %s\n", Fl::event_text());
		color(c);
		redraw();
	}
	return Fl_Window::handle( e_ );
}

int main(int argc, char *argv[]) {
	Window win( 500, 300, "test" );
	int X, Y, W, H;
	Fl::screen_xywh(X,Y,W,H);
	win.position(X,Y);
	win.size(W, H);
	win.resizable(win);
	win.border(0);
	win.show();
	return Fl::run();
}
```
