### ISSUE TITLE
Fl_Graphics_Driver::arc() gets infinite recursion?

### ISSUE THREAD

**Issue by etorth** [fltk/fltk#487]
Any change recently for this function? it gets stack-overflows and looks this function drops into infinte recursion?
Any base/derived class arc() call chaged?

==14282==ERROR: AddressSanitizer: stack-overflow on address 0x7ffffaa83fe8 (pc 0x7fbe5e9ac52c bp 0x7ffffaa84850 sp 0x7ffffaa83ff0 T0)
    #0 0x7fbe5e9ac52c in __interceptor_sincos ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:5011
    #1 0x7fbe5f4a4730 in Fl_Graphics_Driver::arc(double, double, double, double, double) (/home/anhong/b_mir2x/tools/questdesigner/src/questdesigner+0x146730)
    #2 0x7fbe5f4a4776 in Fl_Graphics_Driver::arc(double, double, double, double, double) (/home/anhong/b_mir2x/tools/questdesigner/src/questdesigner+0x146776)
    #3 0x7fbe5f4a4776 in Fl_Graphics_Driver::arc(double, double, double, double, double) (/home/anhong/b_mir2x/tools/questdesigner/src/questdesigner+0x146776)
    #4 0x7fbe5f4a4776 in Fl_Graphics_Driver::arc(double, double, double, double, double) (/home/anhong/b_mir2x/tools/questdesigner/src/questdesigner+0x146776)
    #5 0x7fbe5f4a4776 in Fl_Graphics_Driver::arc(double, double, double, double, double) (/home/anhong/b_mir2x/tools/questdesigner/src/questdesigner+0x146776)
    #6 0x7fbe5f4a4776 in Fl_Graphics_Driver::arc(double, double, double, double, double) (/home/anhong/b_mir2x/tools/questdesigner/src/questdesigner+0x146776)
    #7 0x7fbe5f4a4776 in Fl_Graphics_Driver::arc(double, double, double, double, double) (/home/anhong/b_mir2x/tools/questdesigner/src/questdesigner+0x146776)
    #8 0x7fbe5f4a4776 in Fl_Graphics_Driver::arc(double, double, double, double, double) (/home/anhong/b_mir2x/tools/questdesigner/src/questdesigner+0x146776)
    #9 0x7fbe5f4a4776 in Fl_Graphics_Driver::arc(double, double, double, double, double) (/home/anhong/b_mir2x/tools/questdesigner/src/questdesigner+0x146776)
    #10 0x7fbe5f4a4776 in Fl_Graphics_Driver::arc(double, double, double, double, double) (/home/anhong/b_mir2x/tools/questdesigner/src/questdesigner+0x146776)
    #11 0x7fbe5f4a4776 in Fl_Graphics_Driver::arc(double, double, double, double, double) (/home/anhong/b_mir2x/tools/questdesigner/src/questdesigner+0x146776)
    #12 0x7fbe5f4a4776 in Fl_Graphics_Driver::arc(double, double, double, double, double) (/home/anhong/b_mir2x/tools/questdesigner/src/questdesigner+0x146776)
    #13 0x7fbe5f4a4776 in Fl_Graphics_Driver::arc(double, double, double, double, double) (/home/anhong/b_mir2x/tools/questdesigner/src/questdesigner+0x146776)
    #14 0x7fbe5f4a4776 in Fl_Graphics_Driver::arc(double, double, double, double, double) (/home/anhong/b_mir2x/tools/questdesigner/src/questdesigner+0x146776)
    #15 0x7fbe5f4a4776 in Fl_Graphics_Driver::arc(double, double, double, double, double) (/home/anhong/b_mir2x/tools/questdesigner/src/questdesigner+0x146776)
    #16 0x7fbe5f4a4776 in Fl_Graphics_Driver::arc(double, double, double, double, double) (/home/anhong/b_mir2x/tools/questdesigner/src/questdesigner+0x146776)
    #17 0x7fbe5f4a4776 in Fl_Graphics_Driver::arc(double, double, double, double, double) (/home/anhong/b_mir2x/tools/questdesigner/src/questdesigner+0x146776)
    #18 0x7fbe5f4a4776 in Fl_Graphics_Driver::arc(double, double, double, double, double) (/home/anhong/b_mir2x/tools/questdesigner/src/questdesigner+0x146776)
    #19 0x7fbe5f4a4776 in Fl_Graphics_Driver::arc(double, double, double, double, double) (/home/anhong/b_mir2x/tools/questdesigner/src/questdesigner+0x146776)
    #20 0x7fbe5f4a4776 in Fl_Graphics_Driver::arc(double, double, double, double, double) (/home/anhong/b_mir2x/tools/questdesigner/src/questdesigner+0x146776)
    #21 0x7fbe5f4a4776 in Fl_Graphics_Driver::arc(double, double, double, double, double) (/home/anhong/b_mir2x/tools/questdesigner/src/questdesigner+0x146776)
    #22 0x7fbe5f4a4776 in Fl_Graphics_Driver::arc(double, double, double, double, double) (/home/anhong/b_mir2x/tools/questdesigner/src/questdesigner+0x146776)
    #23 0x7fbe5f4a4776 in Fl_Graphics_Driver::arc(double, double, double, double, double) (/home/anhong/b_mir2x/tools/questdesigner/src/questdesigner+0x146776)
    #24 0x7fbe5f4a4776 in Fl_Graphics_Driver::arc(double, double, double, double, double) (/home/anhong/b_mir2x/tools/questdesigner/src/questdesigner+0x146776)
    #25 0x7fbe5f4a4776 in Fl_Graphics_Driver::arc(double, double, double, double, double) (/home/anhong/b_mir2x/tools/questdesigner/src/questdesigner+0x146776)
    #26 0x7fbe5f4a4776 in Fl_Graphics_Driver::arc(double, double, double, double, double) (/home/anhong/b_mir2x/tools/questdesigner/src/questdesigner+0x146776)
    #27 0x7fbe5f4a4776 in Fl_Graphics_Driver::arc(double, double, double, double, double) (/home/anhong/b_mir2x/tools/questdesigner/src/questdesigner+0x146776)

...

**Comment by etorth** [comment]
a clean rebuild can not reproduce, close this.
