### ISSUE TITLE
Native Filechooser (Zenity) crashes on second invocation

### ISSUE THREAD

**Issue by wcout** [fltk/fltk#665]
System: Ubuntu 20.04

Reproduce:

- Run `examples/nativefilechooser-simple`
- Select once
- Select again => crash

````
Program received signal SIGSEGV, Segmentation fault.
0x00005555555b79cf in Fl_Zenity_Native_File_Chooser_Driver::build_command (this=0x555555691eb0)
    at Fl_Native_File_Chooser_Zenity.cxx:86
86	      *cp = 0;
(gdb) bt
#0  0x00005555555b79cf in Fl_Zenity_Native_File_Chooser_Driver::build_command (this=0x555555691eb0)
    at Fl_Native_File_Chooser_Zenity.cxx:86
#1  0x00005555555b6b0c in Fl_Kdialog_Native_File_Chooser_Driver::show (this=0x555555691eb0)
    at Fl_Native_File_Chooser_Kdialog.cxx:134
#2  0x000055555557ef72 in Fl_Native_File_Chooser::show (this=0x55555568f5c0)
    at Fl_Native_File_Chooser.cxx:239
#3  0x000055555556e800 in Menu_CB(Fl_Widget*, void*) ()
#4  0x00005555555d61f2 in Fl_Menu_Item::do_callback (this=0x5555556818e0, o=0x55555565a260)
    at ../FL/Fl_Menu_Item.H:393
#5  0x00005555555d6c70 in Fl_Menu_::picked (this=0x55555565a260, v=0x5555556818e0)
    at Fl_Menu_.cxx:304
#6  0x000055555557d7fb in Fl_Menu_Button::popup (this=0x55555565a260) at Fl_Menu_Button.cxx:72
#7  0x000055555557d9af in Fl_Menu_Button::handle (this=0x55555565a260, e=1)
    at Fl_Menu_Button.cxx:91
#8  0x00005555555784ee in send (o=0x55555565a260, event=1) at Fl_Group.cxx:96
#9  0x0000555555578c37 in Fl_Group::handle (this=0x55555565a0e0, event=1) at Fl_Group.cxx:226
#10 0x000055555558d1f2 in Fl_Window::handle (this=0x55555565a0e0, ev=1) at Fl_Window.cxx:598
#11 0x0000555555570152 in send_event (event=1, to=0x55555565a0e0, window=0x55555565a0e0)
    at Fl.cxx:1185
#12 0x0000555555570363 in Fl::handle_ (e=1, window=0x55555565a0e0) at Fl.cxx:1324
#13 0x00005555555701f9 in Fl::handle (e=1, window=0x55555565a0e0) at Fl.cxx:1273
#14 0x00005555555afebf in fl_handle (thisevent=...) at Fl_x.cxx:2123
#15 0x00005555555aa616 in do_queued_events () at Fl_x.cxx:116
#16 0x00005555555aa9ae in fd_callback () at Fl_x.cxx:308
#17 0x00005555555e494f in Fl_Unix_Screen_Driver::poll_or_select_with_delay (this=0x55555565a690, 
    time_to_wait=0.85860500000000017) at drivers/Unix/Fl_Unix_Screen_Driver.cxx:74
#18 0x00005555555aa6b5 in Fl_X11_Screen_Driver::poll_or_select_with_delay (this=0x55555565a690, 
    time_to_wait=0.85860500000000017) at Fl_x.cxx:137
#19 0x00005555555e3dd5 in Fl_Unix_System_Driver::wait (this=0x555555659eb0, 
    time_to_wait=0.85860500000000017) at drivers/Unix/Fl_Unix_System_Driver.cxx:751
#20 0x000055555556f339 in Fl::wait (time_to_wait=1e+20) at Fl.cxx:585
#21 0x000055555556f361 in Fl::run () at Fl.cxx:605
#22 0x000055555556e9ba in main ()
````
Obviously the filter string is overwritten from the first invocation and the closing bracket `)` is not found therefore:

````
(gdb) print p
$1 = 0x555555729200 "C++ (*.cxx *.cpp *.h *.H"
(gdb) 
````

**Comment by wcout** [comment]
BTW:
If I start the filechooser with an  ill formatted filter (missing closing bracket)
````diff
-      G_chooser->filter("C++\t*.{cxx,cpp,h,H}\n");
+      G_chooser->filter("C++\t*.{cxx,cpp,h,H\n");
````
there is a also crash.
Shouldn't this be prevented somehow?

**Comment by ManoloFLTK** [comment]
@wcout The commit mentionned above should fix the problem. Please, close issue if you confirm.

**Comment by wcout** [comment]
Yes, this fixes the first part.
But did you see my follow up message?

This leads to:
````
Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff768b859 in __GI_abort () at abort.c:79
#2  0x00007ffff7916911 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff792238c in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff79223f7 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff79226a9 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff7916522 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00005555555b7030 in Fl_Kdialog_Native_File_Chooser_Driver::parse_filter (
    this=0x5555556a5390, f=0x555555725eb0 "C++\t*.{cxx,cpp,h,H")
    at Fl_Native_File_Chooser_Kdialog.cxx:211
#8  0x00005555555b73ac in Fl_Kdialog_Native_File_Chooser_Driver::filter (this=0x5555556a5390, 
    f=0x555555606149 "C++\t*.{cxx,cpp,h,H\n") at Fl_Native_File_Chooser_Kdialog.cxx:250
#9  0x000055555557edea in Fl_Native_File_Chooser::filter (this=0x555555681da0, 
    f=0x555555606149 "C++\t*.{cxx,cpp,h,H\n") at Fl_Native_File_Chooser.cxx:176
#10 0x000055555556e7c7 in Menu_CB(Fl_Widget*, void*) ()
````

**Comment by ManoloFLTK** [comment]
Should be good now.

**Comment by wcout** [comment]
Ok, this is again fixed.
But couldn't resist to probe the parsing a little, and this one crashes:
````diff
--- a/examples/nativefilechooser-simple.cxx
+++ b/examples/nativefilechooser-simple.cxx
@@ -36,7 +36,7 @@ static void Menu_CB(Fl_Widget*,void*data) {
       G_chooser = new Fl_Native_File_Chooser();
       G_chooser->directory(".");                                // directory to start browsing with
       G_chooser->preset_file("nativefilechooser-simple.cxx");   // file to start with
-      G_chooser->filter("C++\t*.{cxx,cpp,h,H}\n");
+      G_chooser->filter("C++\t*.cxx,cpp,h,H{}\n");
       G_chooser->type(Fl_Native_File_Chooser::BROWSE_FILE);     // only picks files that exist
       G_chooser->title("Pick a file please..");                 // custom title for chooser window
     }
````

````
Program received signal SIGSEGV, Segmentation fault.
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
65	../sysdeps/x86_64/multiarch/strlen-avx2.S: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
#1  0x00005555555b7112 in Fl_Kdialog_Native_File_Chooser_Driver::parse_filter (this=0x55555568f300, 
    f=0x555555726e80 "C++\t*.cxx,cpp,h,H{}") at Fl_Native_File_Chooser_Kdialog.cxx:222
#2  0x00005555555b73be in Fl_Kdialog_Native_File_Chooser_Driver::filter (this=0x55555568f300, 
    f=0x555555606149 "C++\t*.cxx,cpp,h,H{}\n") at Fl_Native_File_Chooser_Kdialog.cxx:251
#3  0x000055555557edea in Fl_Native_File_Chooser::filter (this=0x555555681b10, 
    f=0x555555606149 "C++\t*.cxx,cpp,h,H{}\n") at Fl_Native_File_Chooser.cxx:176
#4  0x000055555556e7c7 in Menu_CB(Fl_Widget*, void*) ()
````

**Comment by ManoloFLTK** [comment]
One more.

**Comment by wcout** [comment]
Ok, but one more me too ;)

````
Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff768b859 in __GI_abort () at abort.c:79
#2  0x00007ffff7916911 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff792238c in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff79223f7 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff79226a9 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff7916522 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00005555555b6fcb in Fl_Kdialog_Native_File_Chooser_Driver::parse_filter (
    this=0x55555568f350, f=0x555555725600 "{}C++\t*.cxx,cpp,h,H{}")
    at Fl_Native_File_Chooser_Kdialog.cxx:208
#8  0x00005555555b73cc in Fl_Kdialog_Native_File_Chooser_Driver::filter (this=0x55555568f350, 
    f=0x555555606149 "{}C++\t*.cxx,cpp,h,H{}\n") at Fl_Native_File_Chooser_Kdialog.cxx:251
#9  0x000055555557edea in Fl_Native_File_Chooser::filter (this=0x55555568f590, 
    f=0x555555606149 "{}C++\t*.cxx,cpp,h,H{}\n") at Fl_Native_File_Chooser.cxx:176

````
You see the filter in the backtrace.

I printed out the values before the crash in line 208:
```` 
r=0x55a476216840, p=0x55a476216845, r-p = -5
````

**Comment by ManoloFLTK** [comment]
Last one before closing.
