### ISSUE TITLE
Another segfault of bin/test/forms example under Wayland

### ISSUE THREAD

**Issue by polter-rnd** [fltk/fltk#723]
**Describe the bug**
After some time of playing around with `forms` test, it segfaults. It is not 100% reproducible, and I still don't know the exact order of actions to make i segfault, but I experienced it twice already. It was on secondary monitor (that's important). No fractional scaling enabled.

```
$ bin/test/forms
Segmentation fault (core dumped)
```

**To Reproduce**
1. Run `bin/test/forms` example under Wayland (GNOME)
2. Move the window on secondary monitor
3. Move around between monitors, select different Boxtype, drag controls, etc
4. After some time playing with it, it segfaults:

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000004a4786 in Fl_Wayland_Window_Driver::wait_for_expose (this=0xc51f00)
    at /home/polter/Projects/FLTK/fltk/src/drivers/Wayland/Fl_Wayland_Window_Driver.cxx:820
820	  } else if (xid->kind == DECORATED) {
Missing separate debuginfos, use: dnf debuginfo-install bzip2-libs-1.0.8-12.fc37.x86_64 cairo-1.17.6-2.fc37.x86_64 dbus-libs-1.14.6-1.fc37.x86_64 fontconfig-2.14.1-2.fc37.x86_64 freetype-2.12.1-3.fc37.x86_64 fribidi-1.0.12-2.fc37.x86_64 glib2-2.74.7-1.fc37.x86_64 glibc-2.36-9.fc37.x86_64 graphite2-1.3.14-10.fc37.x86_64 harfbuzz-5.2.0-1.fc37.x86_64 libX11-1.8.4-1.fc37.x86_64 libXau-1.0.10-1.fc37.x86_64 libXrender-0.9.10-17.fc37.x86_64 libblkid-2.38.1-1.fc37.x86_64 libbrotli-1.0.9-9.fc37.x86_64 libcap-2.48-5.fc37.x86_64 libdatrie-0.2.13-4.fc37.x86_64 libffi-3.4.4-1.fc37.x86_64 libgcc-12.2.1-4.fc37.x86_64 libglvnd-1.5.0-1.fc37.x86_64 libglvnd-egl-1.5.0-1.fc37.x86_64 libmount-2.38.1-1.fc37.x86_64 libpng-1.6.37-13.fc37.x86_64 libselinux-3.5-1.fc37.x86_64 libstdc++-12.2.1-4.fc37.x86_64 libthai-0.1.29-3.fc37.x86_64 libwayland-client-1.21.0-1.fc37.x86_64 libwayland-cursor-1.21.0-1.fc37.x86_64 libwayland-egl-1.21.0-1.fc37.x86_64 libxcb-1.13.1-10.fc37.x86_64 libxkbcommon-1.4.1-2.fc37.x86_64 libxml2-2.10.4-1.fc37.x86_64 libzstd-1.5.5-1.fc37.x86_64 lz4-libs-1.9.4-1.fc37.x86_64 pango-1.50.14-1.fc37.x86_64 pcre2-10.40-1.fc37.1.x86_64 pixman-0.40.0-6.fc37.x86_64 xz-libs-5.4.1-1.fc37.x86_64 zlib-1.2.12-5.fc37.x86_64
(gdb) bt
#0  0x00000000004a4786 in Fl_Wayland_Window_Driver::wait_for_expose (this=0xc51f00)
    at /home/polter/Projects/FLTK/fltk/src/drivers/Wayland/Fl_Wayland_Window_Driver.cxx:820
#1  0x0000000000486e89 in Fl_Window::wait_for_expose (this=0x7ffd69811c90)
    at /home/polter/Projects/FLTK/fltk/src/Fl_Window.cxx:465
#2  0x00000000004a5f42 in Fl_Wayland_Window_Driver::makeWindow (this=0xc51f00)
    at /home/polter/Projects/FLTK/fltk/src/drivers/Wayland/Fl_Wayland_Window_Driver.cxx:1276
#3  0x00000000004a2fdf in Fl_Wayland_Window_Driver::show (this=0xc51f00)
    at /home/polter/Projects/FLTK/fltk/src/drivers/Wayland/Fl_Wayland_Window_Driver.cxx:406
#4  0x0000000000487309 in Fl_Window::show (this=0x7ffd69811c90)
    at /home/polter/Projects/FLTK/fltk/src/Fl_Window.cxx:550
#5  0x000000000047e10c in Fl_Single_Window::show (this=0x7ffd69811c90)
    at /home/polter/Projects/FLTK/fltk/src/Fl_Single_Window.cxx:28
#6  0x0000000000470378 in Fl_Menu_Item::pulldown (this=0xc14290, X=110, Y=30, W=130, H=30, initial_item=0x0, 
    pbutton=0xba0af0, title=0x0, menubar=0) at /home/polter/Projects/FLTK/fltk/src/Fl_Menu.cxx:1016
#7  0x0000000000456782 in Fl_Choice::handle (this=0xba0af0, e=1)
    at /home/polter/Projects/FLTK/fltk/src/Fl_Choice.cxx:205
#8  0x000000000045f725 in send (o=0xba0af0, event=1) at /home/polter/Projects/FLTK/fltk/src/Fl_Group.cxx:96
#9  0x000000000045fe30 in Fl_Group::handle (this=0xb9ef50, event=1)
    at /home/polter/Projects/FLTK/fltk/src/Fl_Group.cxx:226
#10 0x00000000004874e0 in Fl_Window::handle (this=0xb9ef50, ev=1)
    at /home/polter/Projects/FLTK/fltk/src/Fl_Window.cxx:598
#11 0x0000000000449a5e in send_event (event=1, to=0xb9ef50, window=0xb9ef50)
    at /home/polter/Projects/FLTK/fltk/src/Fl.cxx:1187
#12 0x0000000000449c44 in Fl::handle_ (e=1, window=0xb9ef50) at /home/polter/Projects/FLTK/fltk/src/Fl.cxx:1326
#13 0x0000000000449af5 in Fl::handle (e=1, window=0xb9ef50) at /home/polter/Projects/FLTK/fltk/src/Fl.cxx:1275
#14 0x00000000004c0f5b in pointer_button (data=0xba7a30, wl_pointer=0xc0c480, serial=21885, time=11764618, 
    button=272, state=1)
    at /home/polter/Projects/FLTK/fltk/src/drivers/Wayland/Fl_Wayland_Screen_Driver.cxx:324
#15 0x00007fdb5eff4a06 in ffi_call_unix64 () from /lib64/libffi.so.8
#16 0x00007fdb5eff149d in ffi_call_int.lto_priv () from /lib64/libffi.so.8
#17 0x00007fdb5eff4083 in ffi_call () from /lib64/libffi.so.8
#18 0x00007fdb5fdc2e53 in wl_closure_invoke.constprop () from /lib64/libwayland-client.so.0
#19 0x00007fdb5fdc35f3 in dispatch_event.isra () from /lib64/libwayland-client.so.0
#20 0x00007fdb5fdc37bc in wl_display_dispatch_queue_pending () from /lib64/libwayland-client.so.0
#21 0x00000000004c3217 in wayland_socket_callback (fd=3, display=0xba1370)
    at /home/polter/Projects/FLTK/fltk/src/drivers/Wayland/Fl_Wayland_Screen_Driver.cxx:1152
#22 0x00000000004bf9e2 in Fl_Unix_Screen_Driver::poll_or_select_with_delay (this=0xba1250, 
    time_to_wait=0.13149200000000008)
    at /home/polter/Projects/FLTK/fltk/src/drivers/Unix/Fl_Unix_Screen_Driver.cxx:74
#23 0x00000000004c68f5 in Fl_Unix_System_Driver::wait (this=0xb9ef10, time_to_wait=0.13149200000000008)
    at /home/polter/Projects/FLTK/fltk/src/drivers/Unix/Fl_Unix_System_Driver.cxx:751
#24 0x0000000000448cb1 in Fl::wait (time_to_wait=1e+20) at /home/polter/Projects/FLTK/fltk/src/Fl.cxx:585
#25 0x0000000000448d10 in Fl::wait () at /home/polter/Projects/FLTK/fltk/src/Fl.cxx:627
#26 0x000000000044732a in fl_do_forms () at /home/polter/Projects/FLTK/fltk/src/forms_compatibility.cxx:121
#27 0x0000000000445d56 in main (argc=1, argv=0x7ffd698128f8)
    at /home/polter/Projects/FLTK/fltk/test/forms.cxx:183
(gdb) p xid
$1 = (wld_window *) 0x0
```

**Expected behavior**
Run without segfaults

**FLTK Version**
 - Version: 1.4.0
 - Downloaded and self-built from: Git
 - If from Git, branch: master
 - If from Git, commit: 52a15632a6b8457fae2a9db61fe346c40bd46f15

**FLTK Configure / Build Options**
 - `cmake -DCMAKE_BUILD_TYPE=Debug -DOPTION_WAYLAND_ONLY=ON ..`

**Operating System / Platform:**
 - OS: Linux
 - OS Version: Fedora 37

**Linux/Unix Runtime, if applicable:**
 - Wayland / GNOME 43

**Additional context**
Core dump:

I've renamed it to `.txt` so github allows me to upload it. It should be renamed to `.tar.xz` and extracted.

[forms-new-debug.tar.xz.txt](https://github.com/fltk/fltk/files/11353399/forms-new-debug.tar.xz.txt)

**Comment by polter-rnd** [comment]
I've managed to find out how to reproduce it. Likely it is caused by this: #724

**Comment by ManoloFLTK** [comment]
I close this because it's now covered by #724
