### ISSUE TITLE
Certain html can cause html widget to coredump

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#871]
**Describe the bug**
Not sure exactly why, but the attached [foo.html](https://github.com/fltk/fltk/files/13707468/foo.html.txt) file causes the FLTK html widget to crash.

This can also be shown with the "test/help_dialog" program, e.g.

    cd build
    ./bin/test/help_dialog /var/tmp/foo.html

It might be because there's an extra `</UL>`, but whatever it is, **it shouldn't crash.**

Here's a stack trace:
```
#0  Fl_Int_Vector::pop_back() (this=0x7fffffffab10) at /usr/local/src/fltk-1.4.x.git/src/Fl_Int_Vector.H:144
#1  0x0000000000440af5 in Fl_Help_View::format() (this=0x562d00) at /usr/local/src/fltk-1.4.x.git/src/Fl_Help_View.cxx:1557
#2  0x0000000000447095 in Fl_Help_View::load(char const*) (this=0x562d00, f=0x7fffffffe89e "/var/tmp/foo.html") at /usr/local/src/fltk-1.4.x.git/src/Fl_Help_View.cxx:3331
```

**Comment by erco77** [comment]
Closing.
Seems like the assert() is a todo item..
